### ISSUE TITLE
guitar hero 2 

### ISSUE THREAD

**Issue by iamjen023** [TheRealDannyyy/Phase-Shift-Theme-Ports#40]
could you try to create a guitar hero 2 theme

**Comment by TheRealDannyyy** [comment]
I'm currently not creating themes, only porting existing broken ones.
I might start creating themes once I'm done with all ports and the game is available again.

**Comment by TheRealDannyyy** [comment]
This also exists:
http://dwsk.proboards.com/thread/1808/work-progress-guitar-hero-theme
